### ISSUE TITLE
Различные правки

### ISSUE THREAD

**Issue by Frolikow** [EvgeniyChuprov/UI-KIT#10]
1)Не совсем понятно почему на "соседних" строчках, то i то item. Старайся всегда в одном стиле писать. В данном случае лучше item
![image](https://user-images.githubusercontent.com/25764783/62199936-9d860c00-b3ae-11e9-87f7-9b7b9d2a1990.png)
2) Не лучший вариант именования лучше использовать просто element. приставка dom излишняя, и сокращение уберется(а это большой плюс)
![image](https://user-images.githubusercontent.com/25764783/62200244-34eb5f00-b3af-11e9-92b8-8d165a4f44bb.png)
3) Не сразу понятно что такое $first а данном случае. Первый пузырек? Пришлось в браузере смотреть что это за элемент. В данном случае лучше явно назвать ширина первого шага(например)
![image](https://user-images.githubusercontent.com/25764783/62200479-b7741e80-b3af-11e9-82e6-6bb8bc4cce7b.png)
4) именовать обработчики событий следует по шаблону hanldeElementNameEventName. 
![image](https://user-images.githubusercontent.com/25764783/62202241-243ce800-b3b3-11e9-83a1-7411fbab1feb.png)
И здесь не сразу можно понять что написано, ты вешаешь событие клика на элемент рипл?, мне кажется элемент рипл должен появлятся после клика по кнопке. Поправь, если я не правильно понял твой замысел.
5) ну и важный момент по БЭМу. У блоков не должно быть внешней геометрии. Если нужно задавать отступы, то лучше их дать родительскому элементу в котором лежит блок(обертке, проще говоря). А сам блок будет просто внутри этого элемента и без ненужных отступов

**Comment by EvgeniyChuprov** [comment]
> И здесь не сразу можно понять что написано, ты вешаешь событие клика на элемент рипл?

Да, так и было. Сменил активацию эффекта при нажатии на кнопку. Надеюсь правильно назвал подключаемый к кнопке класс "button_effect_ripple" и обработчик "_handleButtonRippleEffect".

**Comment by EvgeniyChuprov** [comment]
> 5) ну и важный момент по БЭМу.

В блоках оставлял только padding и margin: auto - так тоже нельзя или где то что то пропустил?

**Comment by Sergio-Ka** [comment]
1. А где здесь "_handleButtonRippleEffect" имя события (EventName)? Наверное _handleButtonClick?
2. Нельзя использовать margin вообще у блоков. Padding формально можно использовать, но нужно понимать, что это часть внешнего вида блока. То есть если ты его где-то в другом проекте захочешь переиспользовать - ты padding менять не должен в этом случае, а если ты вынужден его поменять, значит ты с помощью pаdding выстраивал элементы. А если ты его пользуешь для дистанцирования от соседних блоков - это плохо.

**Comment by Frolikow** [comment]
По моим замечаниям все ок кроме именования обработчиков) и к ним же добавлю именование методов.
Пример:
![image](https://user-images.githubusercontent.com/25764783/62693778-4e1e8c00-b9fd-11e9-8bdf-9257d428d811.png)
что не так:
1) имя метода `_ripples`. Имя метода обязательно должно содержать глагол, т.к. метод всегда подразумевает какое-то действие. Ты в данном случае вешаешь обработчики внутри метода, стоит подумать как назвать метод чтоб он описывал свои действия. 
2) обработчик `_handleButtonRippleEffect`, давай разберем на примере: 
 есть такая строка
```js
this.$button.on('click', this._handleButtonRippleEffect.bind(this));
```
откуда здесь риплЭффект? у тебя есть кнопка `this.$button` и есть событие на эту кнопку `'click'`. именно это происходит в обработчике, т.е. имя будет `handleButtonClick`.
А дальше, если тебе не нравиться что обработчик называется так, а внтури идет логика с перерисовкой элементов и еще что-то. То можно логику создания риплЭффекта вынести в свой метод, и тогда внутри обработчика просто вызывать этот метод. надеюсь не замудрено написал,если что спрашивай))
3) следующий обработчик тоже ошибка
```js
this.$button.on('animationend webkitAnimationEnd oanimationend MSAnimationEnd', this._delClass.bind(this));
```
есть `button`, есть событие `'animationend'`. Почему delClass. зачем эта информация. Нам важно что есть обработчик, и где-то в коде мы можем его увидеть и только по названию догадаться где он вызывается)) 

p.s. такие ошибки встречаются и в других файлах, например в `stages` лежит метод `_stages` , имя существительное.
Поправь по всему проекту )

**Comment by Frolikow** [comment]
по моим замечаниям ок, если у Сергея(@Sergio-Ka ) нету вопросов, то можно закрывать ишью

**Comment by Frolikow** [comment]
У Сергея(@Sergio-Ka ), по всей видимости вопросов нету) 
А я добавлю замечаний немного)
1) Очень сбивает с толку именование этой переменной. "стрелка вправо" - ок. НО, она ведь по факту мб и "влево") тут прям напрашивается переименовать в соответствии со строкой которая в ней будет лежать)
```pug
  - arrowRight += right ? " arrow-button__arrow_direction_right"  : " arrow-button__arrow_direction_left";
```
___
2) Не стоит делать разные отступы в одном проекте. Либо табы, либо пробелы(лучше пробелы)...мешать не надо. 
![image](https://user-images.githubusercontent.com/25764783/65879734-aef19180-e3ba-11e9-850b-09a5d061243b.png)
___
3)  **check**. Странное имя. Глагол предполагает какую-то функцию. Точно не подумал бы что там булево значение лежит.
```pug
mixin tick(options)
  - let {name= "name", id="id", check= false} = options;

  .tick
    input.tick__input(type="radio" name= name  id= id  checked= check)
    label.tick__label(for= id)
```
___
4) Сущность, которая по БЭМу является элементом, названа блоком. Мне кажется это как минимум не логичным. И вообще слово block для именования, такое же не содержательное как всякие `data, value` в js. Надо придумать более осмысленное имя для элемента. Подобный `block` по всему проекту встречается
```pug
      .users-profiles__block
```

**Comment by Sergio-Ka** [comment]
Не, у меня вопросов нет.

**Comment by Frolikow** [comment]
https://github.com/EvgeniyChuprov/UI-KIT/blob/45473750a1e90d2cecad1596089fe4497ed4c69f/src/blocks/tick/tick.pug#L2
почему именно option? получается что есть `опция` которая по дефолту `false`..,странно. Назови лучше переменную isChecked. То что надо для булевой переменной

Переименуешь - закрывай ишью
