### ISSUE TITLE
JS и т.д.

### ISSUE THREAD

**Issue by Sergio-Ka** [EvgeniyChuprov/UI-KIT#2]
1. Переписать js на классы ES6.
2. Код должен соответствовать стандартам fsd, в том числе и по оформлению. (в стандартах отсылка к стайлгайду AirBnB - в том числе). То есть никаких var, ++ и так далее. Лучше поставить ESlint и настроить его на правила AirBnB.

**Comment by Sergio-Ka** [comment]
1. BubbleSlider
1.1. У тега label в атрибуте for  указывается id инпута к которому метка относится, то есть qqq в данном случае, если мне не изменяет память, а сейчас там тип почему-то. `label.custom-rangeslider__tooltip( id="www" for="range") 0`
1.2. Здесь плохо:
```
$('.custom-rangeslider').each(() => {
  const domEl = {
    range: document.querySelector('.custom-rangeInput'),
    tool: document.querySelector('.custom-rangeslider__tooltip'),
  };
  new BubbleSlider(domEl);
});
```
Смысл этих строк в том, что ты сначала выбираешь все селекторы, потом по ним пробегаешься и создаешь инстанс для каждого, тем самым инкапсулируешь состояние, и если бы у тебя не один слайдер такого типа был, а несколько с одинаковыми классами .custom-rangeslider на странице, например 100, то у тебя это бы не сработало, точнее у всех были бы настройки самого верхнего сладйера, потому что вот здесь range: document.querySelector('.custom-rangeInput'), tool: document.querySelector('.custom-rangeslider__tooltip'), ты выбираешь классы в документе во всем, а не в конкретном элементе, который выбирается на каждой итерации foreach. Надо примерно так
```
$('.custom-rangeslider').each((index, domElement) => {
  const domEl = {
    range: domElement.querySelector('.custom-rangeInput'),
    tool: domElement.querySelector('.custom-rangeslider__tooltip'),
  };
  new BubbleSlider(domEl);
});
```
1.3. -20 / (this.range.max - this.range.min) + 10 + 8
Это какие-то магические и непонятные числа. И почему например 10+8, а не 18? Обычно если возникает необходимость в таких вещах, то эти цифры выносятся в константы, самим константам дается осмысленное название. Обычно создается модуль в котором в объекте по именам лежат такие числа. Модуль импортируется в файл, там же сразу декомпозиция нужных констант происходит и уже использование. Тут наверное будет много файлов, потому просто константы можно, а вот в 3 проекте стоит сделать один общий файл констант, если таковые будут необходимы.
1.4. длина строк, стандарты fsd, air-bnb. 11 страка в js имеет у тебя длину 213 знакомест.
**2. RangeSlider**
2.1. То же замечание про длину строк
2.2. в этой длинной строке вместо конкатенации через знак + использовать темплейт строку.
**3. ButtonRipple**
3.1. риппл должен быть не на всех кнопках, а значит должен быть модификатор, который должен передаваться параметром.
**4. Calendar**
4.1. Опять примерно те же замечания. Ты при создании инстанса передаешь ссылку на конкретный элемент внутрь его, с ней и надо работать,  а не ходить внутри класса по всему документу и брать любые элементы дома. Настройки такого рода `$.datepicker._goto` как я понимаю берут свойство в глобальном объекте $. И зачем вот здесь `$(calendar).datepicker(this.getCalendar());` у тебя используется $() если calendar у тебя и так уже объект jQuery? При этом в первой строке этого метода ты берешь calendar как параметр метода, а в третьей - уже this.calendar. Надо причесать.
**5. Stage**
5.1. То же замечание, что внтури класса нужно селектится не по всему документу, а только в рамках конкретного элемента.
**Общие вопросы**
1. везде посмотри,  что элементы jQuery по стандартам должны иметь префикс $.
2. Глянуть все замечания перекрестно, то есть от одного элемента замечания посмотреть в остальных.
3. Линтер на index.js ругается, где-то лишние пробелы, где то строки, где-то пробелов не хватает.

**Comment by EvgeniyChuprov** [comment]
Настройки такого рода $.datepicker._goto как я понимаю берут свойство в глобальном объекте $.

По умолчанию нажатие кнопки Today просто переносит на текущий месяц без выделения текущей даты. На stackoverflow нашел такой вариант:
I think the best way to handle this is to override the _goToToday method outside of the library itself. This solved the issue for me:

var old_goToToday = $.datepicker._gotoToday
$.datepicker._gotoToday = function(id) {
  old_goToToday.call(this,id)
  this._selectDate(id)
}
Simple and doesn't require you to hack up any events or change any underlying functionality
 https://stackoverflow.com/questions/1073410/today-button-in-jquery-datepicker-doesnt-work

**Comment by Sergio-Ka** [comment]
Еще пара замечаний. 
1. Там в стандартах есть правило, что конструктор должен быть максимально лековесным. У тебя сейчас в Stage (для примера, в остальных так же) следующие строки:
```
constructor($domEl) {
    this.$stage = $domEl;
    this.$stageStep = $domEl.children();
    this.$first = $domEl.children().first();
    this.stages();
  }
```
По сути ты должен оставить только первую строку. Все остальные выборки делать в отдельном методе, например назвать его как-нибудь stageInit(), и уже в нем делать выборки по DOMу и в нем же думаю запускать this.stages(), то есть у тебя по сути в конструкторе будет всего 2 строки.
2. Тут по хорошему все эти методы для внутренних нужд, то есть приватные. А приватные методы нужно именовать начиная с со знака подчеркивания, то есть _имяМетода. Это в стандартах есть.

**Comment by Sergio-Ka** [comment]
Я так подозреваю, что у тебя там все тупо методы приватные ибо снаружи класса они не используются, единственный метод который мог бы быть публичным и который ты сейчас таки запускаешь в конструкторе смысла нет никакого дергать снаружи. В смысле это метод инициализации.
