### ISSUE TITLE
Ошибки при сборке

### ISSUE THREAD

**Issue by Frolikow** [EvgeniyChuprov/UI-KIT#6]
Нужно убрать все ошибки, которые возникают при сборке проекта
![image](https://user-images.githubusercontent.com/25764783/60944127-29f26100-a312-11e9-9a9a-379c9a1b3e64.png)
![image](https://user-images.githubusercontent.com/25764783/60944143-34acf600-a312-11e9-9b7f-a933fec11547.png)
![image](https://user-images.githubusercontent.com/25764783/60944157-3bd40400-a312-11e9-8b82-d8c740ac3aec.png)
![image](https://user-images.githubusercontent.com/25764783/60944172-4393a880-a312-11e9-8301-a0937e53af33.png)

**Comment by EvgeniyChuprov** [comment]
Странно. Только что специально клонировал репозиторий и собрал. Даже шрифтов с заглавной буквы нет:
![image](https://user-images.githubusercontent.com/36810364/60951970-f5c37400-a302-11e9-89ff-3396758794b5.png)
команда npm run start
![image](https://user-images.githubusercontent.com/36810364/60952153-666a9080-a303-11e9-8bd3-39c3054ab5ac.png)
команда npm run build
![image](https://user-images.githubusercontent.com/36810364/60952349-c6613700-a303-11e9-92ea-7d68a2278804.png)

**Comment by Sergio-Ka** [comment]
Шрифты здесь в репозитории кстати лежат и с большой буквы так же, надо подчистить:
![image](https://user-images.githubusercontent.com/33621369/61023193-1a871c80-a3d3-11e9-83a1-01eb17311b4b.png)
Эта ерунда и выдает часть ошибок.
Вторая часть - у тебя слово slider написано с большой буквы в импортах здесь:
![image](https://user-images.githubusercontent.com/33621369/61023646-fd534d80-a3d4-11e9-87cd-f8f937deefc4.png)

**Comment by Sergio-Ka** [comment]
И кстати опиши все команды в README.md, а то например npm run build нет, prod тоже нет.

**Comment by Frolikow** [comment]
Я стягиваю актуальную версию проекта перед каждой проверкой. Одна ошибка - та, что Сергей выше описал, проблема в заглавной букве при импорте.
остальные варнинги из-за шрифтов. Опять же Сергей выше писал, что они у тебя и в репе лежат

**Comment by EvgeniyChuprov** [comment]
Меня удивляет, почему он у меня не ругался при сборке не смотря на ошибки?

**Comment by Frolikow** [comment]
Возможно какие-то изменения не залил на гитхаб, отсюда и разное поведение проектов.

по поводу команд вместо `npm run webpack` лучше сделать `npm run build` или `npm run prod`

**Comment by Sergio-Ka** [comment]
Тут теперь нормально, единственное:
`И кстати опиши все команды в README.md, а то например npm run build нет, prod тоже нет`

**Comment by EvgeniyChuprov** [comment]
> Тут теперь нормально, единственное:
> И кстати опиши все команды в README.md, а то например npm run build нет, prod тоже нет

Я их удалил т.к. не использовал (webpack собирал по гайду и повторял все что там делали). Или нужно вернуть и расписать?

**Comment by Frolikow** [comment]
> > Тут теперь нормально, единственное:
> > И кстати опиши все команды в README.md, а то например npm run build нет, prod тоже нет
> 
> Я их удалил т.к. не использовал (webpack собирал по гайду и повторял все что там делали). Или нужно вернуть и расписать?

Отвечу вопросом) Новый человек подключается к твоему проекту, как ему узнать какими командами все делать? открывать package.json? в нем может быть over-много информации среди которой искать - не вариант. Еще вариант просмотреть гайд по которому ты настраивал проект) 
В общем, файл readme обязателен в любом проекте. В нем обязательно должно быть описание команд для запуска сборки. Тогда подключаясь к проекту можно будет не тратить время на поиск этих самых команд.

**Comment by EvgeniyChuprov** [comment]
Не понимаю, что не так.  На данный момент в  package.json у меня всего 2 команды - запуск dev-server и сборка готового билда. В readme они есть:
![image](https://user-images.githubusercontent.com/36810364/61621644-fc93a480-ac7b-11e9-8ce6-9b5fa229c97e.png)

**package.json**
![image](https://user-images.githubusercontent.com/36810364/61622386-5a74bc00-ac7d-11e9-83a1-83cda07b8152.png)

**Comment by Sergio-Ka** [comment]
Это сейчас у тебя в package.json две команды, а на момент написания замечания было несколько команд. В принципе, если теперь так package.json выглядит, то не актуально уже это замечание. Егор наверное закроет, если у него замечаний нет больше.

**Comment by Frolikow** [comment]
> Не понимаю, что не так. На данный момент в package.json у меня всего 2 команды - запуск dev-server и сборка готового билда. В readme они есть:

так, сейчас по комитам посмотрел историю файла, по всей видимости я не туда куда-то глянул и соответственно ошибочно писал) сори) ишью закрываю
