### ISSUE TITLE
БЭМ

### ISSUE THREAD

**Issue by Frolikow** [EvgeniyChuprov/UI-KIT#7]
Внутри каждого миксина должен лежать только 1 блок который возвращается этим миксином. 
Имя папки где лежит миксин, имя миксина и имя блока в миксине должны совпадать. 

![image](https://user-images.githubusercontent.com/25764783/61187759-9fa65600-a69f-11e9-9b71-fe82b9f7b93b.png)
Здесь очень странно, почему на блоке висят модификаторы элемента?

Здесь очень странный модификатор, и почему он сам по себе? что он модифицирует?(такие места по проекту еще попадаются)
```pug
  .wrap
    .wrap__block
      +header({header:calendarhead})
      .wrap__block_element
        +calendar(calendar)
```

**Comment by Sergio-Ka** [comment]
Замечание по БЭМ. У тебя в ui-kit.pug есть явные блоки content и forms. Оформи это как блок, то есть в отдельную папку и все реализации блока там. У тебя тогда и папка style из корня уйдет вместе с ui-kit.scss.

**Comment by Sergio-Ka** [comment]
Вот кстати еще. Тут как-то странно выглядит с точки зрения БЭМ и менования:
```
mixin button-ripple(options) 
  - let {text="text", small=true, green=true, bRipple=false, fillGreen=false, fillRed=false} = options;
  - let butRipple = "button-ripple";
  - let ripple = "element-ripple";
  - ripple += bRipple ? " js-ripple" : "" ;
  - butRipple += small ? " button-ripple__element_size_small" : "" ;
  - butRipple += green ? " button-ripple__element_color_green" : " button-ripple__element_color_red" ;
  - butRipple += fillGreen ? " button-ripple__element_color_fill-green" : "" ;
  - butRipple += fillRed ? " button-ripple__element_color_fill-red" : "" ;

  button(class= butRipple)= text
    div(class= ripple)
      span.element-ripple__circle
```
1. Что за модификаторы такие вида button-ripple__element_size_small? Может быть button-ripple__element-size_small? Да ви вообще это element здесь лишний, имхо.
2. Кнопка здесь просто button, максимум standard-button, вряд ли button-ripple. На ней рипл вообще не обязателен. Это на тему именования.
3. js-ripple здесь не модификатор. И вообще выглядит как-то подозрительно. Вообще то что с префиксом js это микс по сути. Только он стили не добавляет, а дает возможность выбирать элементы в DOM с помощью js, и если js составляющая убирается - убираются и эти миксы, но внешний вид не портится, на них потому что стили никакие не вешаются (в смысле на классы с префиксом js-). И его по хорошему на кнопку вешать, а не на ее кишки. А уже внутри твоего js файла при переборе и создании инстансов ты берешь только то что с индексом js, а скрипт уже сам там внутри этого элемента смотрит какие брать элементы и как их изменять.

**Comment by Sergio-Ka** [comment]
Егор уже написал про предыдущее замечание частично, я не заметил, но все же у меня там несколько более обширно про другое написано, потому пусть висит, его тоже надо учесть. Посмотрел по проекту и заметил что в целом много такого:
![image](https://user-images.githubusercontent.com/33621369/61530113-5b270b80-aa4d-11e9-9fbf-be1756a85aed.png)
Вот тут например discount__slider-range нормально именован, а вот ниже bubble и coupon - не пойми что, то ли модификатор весящий в воздухе без элемента, то ли опечатка. Надо посмотреть на этот предмет весь проект внимательно, это важно.

**Comment by Frolikow** [comment]
Во многих блоках ошибки с БЭМом есть.
1) Блок внутри блока. Если у тебя две независимых сущности то должно быть два отдельных блока в отдельных файлах. Если одна из них яв-ся частью другой, то значит одна из сущностей должна быть блоком, а другая элементом этого блока. Если у тебя еще не сложилось полное понимание БЭМа, то лучше еще раз изучить его, более вдумчиво
![image](https://user-images.githubusercontent.com/25764783/61578036-ab1fd400-ab1a-11e9-9ece-0260a8a17c6b.png)
2) Опять блок внутри блока
![image](https://user-images.githubusercontent.com/25764783/61578047-e5897100-ab1a-11e9-8fae-fa7a8635021b.png)
3) блок внутри блока
![image](https://user-images.githubusercontent.com/25764783/61578075-4fa21600-ab1b-11e9-9b1c-11f5cd6dc767.png)
4) блок внутри блока и одиночный модификатор( модификатор не может существовать сам по себе, он обязательно должен что-то модифицировать)
![image](https://user-images.githubusercontent.com/25764783/61578097-a0197380-ab1b-11e9-9cf7-b0c2872ef16e.png)
5) из  7-ми сущностей 7 блоков
![image](https://user-images.githubusercontent.com/25764783/61578189-34d0a100-ab1d-11e9-9d8c-94b3636fac86.png)
6) опять ошибки с блоками
![image](https://user-images.githubusercontent.com/25764783/61578202-5fbaf500-ab1d-11e9-903d-bdafde82f9d4.png)
7) блок в блоке
![image](https://user-images.githubusercontent.com/25764783/61578207-86792b80-ab1d-11e9-98eb-6c969f919362.png)
8) опять ошибки с блоками
![image](https://user-images.githubusercontent.com/25764783/61578215-a4df2700-ab1d-11e9-9bbf-95f778bb0684.png)
9) блоки
![image](https://user-images.githubusercontent.com/25764783/61578220-b3c5d980-ab1d-11e9-9b92-4cfe30967333.png)
10) блоки
![image](https://user-images.githubusercontent.com/25764783/61578221-bc1e1480-ab1d-11e9-9538-d486739f9550.png)
11) блоки
![image](https://user-images.githubusercontent.com/25764783/61578225-ca6c3080-ab1d-11e9-8a12-511b245bcac2.png)
12) блоки и одиночные модификаторы
![image](https://user-images.githubusercontent.com/25764783/61578231-d9eb7980-ab1d-11e9-8af9-0dcf0a338823.png)
13) блоки и одиночные модификаторы
![image](https://user-images.githubusercontent.com/25764783/61578235-ea9bef80-ab1d-11e9-9aaa-c85d84f58cd9.png)
14) примеси по стандартам не разрешены
![image](https://user-images.githubusercontent.com/25764783/61578240-069f9100-ab1e-11e9-8bc5-9468e44e328d.png)
15) блоки
![image](https://user-images.githubusercontent.com/25764783/61578241-16b77080-ab1e-11e9-8b0a-4946c51f5bd7.png)
16) блоки и одиночные модификаторы
![image](https://user-images.githubusercontent.com/25764783/61578242-2636b980-ab1e-11e9-885e-c0db4b7504a3.png)
17) блоки
![image](https://user-images.githubusercontent.com/25764783/61578263-46ff0f00-ab1e-11e9-8bb3-f55b310e6a4a.png)
18) блоки 
![image](https://user-images.githubusercontent.com/25764783/61578286-8594c980-ab1e-11e9-805b-b7b99fea24a3.png)
___
p.s. Скорее всего это не все ошибки, что я нашел. Лучше проверь все файлы проекта, чтоб не возвращаться к этим проблемам.

**Comment by Frolikow** [comment]
+ два блока внутри одного миксина
![image](https://user-images.githubusercontent.com/25764783/61711608-a52a2d00-ad7e-11e9-9ae2-6e40e2464284.png)
+ `.toggles-tick__box` тут понятно что за блок, но что за элемент box не совсем понятно, какбудто это продолжение имени блока. Надо подумать как заметить более осмысленно
+ видимо опечатка (tile)
![image](https://user-images.githubusercontent.com/25764783/61712308-3cdc4b00-ad80-11e9-8bd7-151c70d299f4.png)
+ Не понятно что значит модификатор. Блок `stage`, элемент `steps` , а модификатор `color`? Что значит? наверно логичнее было бы назвать, например `filled`. Хотя я бы и вместо steps написал что-то вроде point(именно в единственном числе)
![image](https://user-images.githubusercontent.com/25764783/61712656-fe935b80-ad80-11e9-884f-b547b042c446.png)
+ как будто шпион html проник в pug
![image](https://user-images.githubusercontent.com/25764783/61712995-bf193f00-ad81-11e9-8ead-5b1bed510fbc.png)
+ Здесь выглядит костыльно. `_off` и `_on`, обязательно нужны эти модификаторы? 
![image](https://user-images.githubusercontent.com/25764783/61713066-ea9c2980-ad81-11e9-82bf-1019afe5737e.png)

в остальном по БЭМу пока все

**Comment by Frolikow** [comment]
Так, а теперь объяснишь новое именование ?))
![image](https://user-images.githubusercontent.com/25764783/61787316-bedc7a80-ae39-11e9-8764-a452a303870a.png)

**Comment by EvgeniyChuprov** [comment]
Перфект инглиш он такой )

**Comment by Sergio-Ka** [comment]
Еще немного:
1.Здесь плохо. У тебя map__menu получается элементом, который висит в воздухе. Надо сделать оборачивающий элемент map, а внутри него по мимо map__menu должен быть еще элемент, на который вешается карта. Но в класс ты передаешь внешний оборачивающий элемент, а тот на который повесить карту скрипт смотрит сам уже внутри этого внешнего элемента.
```
  .map.js-map( data-marker= marker data-lat= lat data-lng= lng data-zoom= zoom)
  .map__menu 
    .map__head= title
    .map__address= city
    .map__icon
      .map__location
      .map__pin
```
2. Чегой-то ссылки здесь и изображения без css-класса, а это есть в стандартах:
```
  .message
    .message__header
      .message__chat
        a(href="/mock-address/change-me/", target="_blank", rel="noopener noreferrer")
          img(src=require("./blocks/message/img/chat.png") alt="chat icon")
      .message__camera
        a(href="/mock-address/change-me/", target="_blank", rel="noopener noreferrer")
          img(src=require("./blocks/message/img/camera.png") alt="camera icon")
      .message__name Sarah Brown
      img(class="message__photo" src= photo alt="User photo")
```
А здесь img(class="message__photo" src= photo alt="User photo") надо пользовать точечную нотацию для класса, типа img.message__photо(src= photo alt="User photo")
3. Здесь надо повешать префикс js на корневой элемент, а в скрипт передавать уже его и в нем выбирать внутри нужные элементы для работы с скриптом.
```
  .range-slider
    input.range-slider__range.js-range-slider__range( type="range" min= min max= max value= value step= step)
    .range-slider__scale
      -for (let i = min; i <= max; i += step) {
        .range-slider__digit= i
      -}     
```
4. Здесь для button пользовать тоже точечную нотацию
```
  .search
    input(class= classSearch type="text" name="search" placeholder= placeholder)
    button(class="search__button" type="submit")
```
5. Едва ли тут модификатор none хорошая идея с точки зрения грамотности языка. Тут больше подходит так .select__option_selected
```
  .select.js-select
    select.select__block(name="select" )
      option.select__option.select__option_none(disabled selected) Choose an option
``` 
6. Вряд ли здесь ссылка a с классом link является блоком. А если является, то почему не оформлена миксином в отдельной папке? Думаю это элемент по смыслу и надо сделать значит нормальный класс для него. И кстати использовать точечную нотацию для записи.
```
        menu.site-header__menu
          each item in menu
            li.site-header__menu-element
              a(href= item.link class="link")= item.title  
```
7. Здесь тоже надо какой-то оборачивающий блок, потому что с точки зрения БЭМ элемент висит в воздухе, не смотря на то, что это корректно с точки зрения html
```
  input.tick(type="radio" name= name  id= id  checked= check)
  label.tick__label(for= id)
```
8. Здесь опять какой-то не идентифицированный input без класса
```
  label.toggle
    input( id="switch" type="checkbox"  checked= check)

    .toggle__on-off                          
    .toggle__ball
```
9. А здесь тоже ссылка и изображение без классов на последних двух строчках
```
  -  theme += color === "green" ? " user-profile__tooltip_green" : "";

  .user-profile
    img.user-profile__image(src= img alt="User photo")

    div(class= theme)
      .user-profile__name= name
      .user-profile__job= job

      .user-profile__social
        each item in socialNetwork
          - let {websiteAddress="/mock-address/change-me", websiteImg="", imgAlt=""} = item

          a(href= websiteAddress, target="_blank", rel="noopener noreferrer")
            img(src= websiteImg alt= imgAlt)
```
А вот это именование опять не очень user-profile__tooltip_green Опять вспоминаем про то что модификаторы двух типов бывают. И этот - явно не булевый, а стало быть ключ-значение, а если так, то значение есть, но где тогда ключ?

**Comment by Sergio-Ka** [comment]
ОК. Закрывай сам этот issue.
